### ISSUE TITLE
Error when running main.py

### ISSUE THREAD

**Issue by bagindokemas** [takuo-h/GNN-for-OOKB#8]
Dear Authors,

I found this error when I executed your main.py:
Namespace(activate='relu', alpha0=0, alpha1=0, alpha2=0, alpha3=0, auxiliary_file='datasets/standard/WordNet11/serialized/train', batch_size=5000, beta0=0.01, beta1=0.0001, dev_file='datasets/standard/WordNet11/serialized/dev', dim=200, dropout_block=0.0, dropout_decay=0.0, dropout_embed=0.0, entity_size=38194, epoch_size=1000, gpu_device=0, is_balanced_tr=False, is_batchnorm=True, is_bernoulli_trick=True, is_bound_wr=True, is_embed=True, is_known=False, is_residual=False, layerR=1, margin_file='', nn_model='A0', objective_function='absolute', opt_model='Adam', order=1, param_dir='', pool_size=640, pooling_method='max', rel_size=11, sample_size=64, seed=0, test_batch_size=20000, test_file='datasets/standard/WordNet11/serialized/test', threshold=300.0, train_file='datasets/standard/WordNet11/serialized/train', train_size=1000, use_gpu=False) 

main.py 

15:23:05 load train 

15:23:06 set axiaulity 

15:23:06 standard setting, use: edges=links 

15:23:06 load train 

15:23:06 load dev 

dev size: 4880 

15:23:06 load test 

test size: 19746 

relation size: 11 entity size: 38194 

Traceback (most recent call last): 

  File "main.py", line 330, in <module> 

    main(args) 

  File "main.py", line 242, in main 

    trLoss,Ntr = train(args,m,xp,opt) 

  File "main.py", line 187, in train 

    loss = m.train(positive,negative,glinks,gold_relations,gedges,xp) 

  File "/home/ktgroup/Documents/kems/Tools/GNN-for-OOKB/1-starndard-setting/models/ModelA0.py", line 256, in train 

    x = self.get_context(entities,links,relations,edges,0,xp) 

  File "/home/ktgroup/Documents/kems/Tools/GNN-for-OOKB/1-starndard-setting/models/ModelA0.py", line 240, in get_context 

    x = getattr(self,self.forwardB[order][0])(x,neighbor,neighbor_dict,assign,entities,relations) 

  File "/home/ktgroup/Documents/kems/Tools/GNN-for-OOKB/1-starndard-setting/models/ModelA0.py", line 163, in __call__ 

    if r%2==0:    rx = getattr(self,self.forwardH[r//2][0])(rx) 

  File "/home/ktgroup/Documents/kems/Tools/GNN-for-OOKB/1-starndard-setting/models/ModelA0.py", line 37, in __call__ 

    x = getattr(self,name)(x) 

  File "/home/ktgroup/Documents/kems/Tools/GNN-for-OOKB/1-starndard-setting/models/ModelA0.py", line 19, in __call__ 
    if self.dropout_rate!=0: 
**AttributeError: 'Module' object has no attribute 'dropout_rate'** 

Could you advise me what changes that I need to do on your code to make main.py running? 

Thank you very much,
Kem

**Comment by Tianchen627** [comment]
Have you figured it out?My solution is commenting out all the duplicate code(from line 11 to line 303) in ModelA0.py.
I wonder if there is a better one.

> Dear Authors,
> 
> I found this error when I executed your main.py:
> Namespace(activate='relu', alpha0=0, alpha1=0, alpha2=0, alpha3=0, auxiliary_file='datasets/standard/WordNet11/serialized/train', batch_size=5000, beta0=0.01, beta1=0.0001, dev_file='datasets/standard/WordNet11/serialized/dev', dim=200, dropout_block=0.0, dropout_decay=0.0, dropout_embed=0.0, entity_size=38194, epoch_size=1000, gpu_device=0, is_balanced_tr=False, is_batchnorm=True, is_bernoulli_trick=True, is_bound_wr=True, is_embed=True, is_known=False, is_residual=False, layerR=1, margin_file='', nn_model='A0', objective_function='absolute', opt_model='Adam', order=1, param_dir='', pool_size=640, pooling_method='max', rel_size=11, sample_size=64, seed=0, test_batch_size=20000, test_file='datasets/standard/WordNet11/serialized/test', threshold=300.0, train_file='datasets/standard/WordNet11/serialized/train', train_size=1000, use_gpu=False)
> 
> main.py
> 
> 15:23:05 load train
> 
> 15:23:06 set axiaulity
> 
> 15:23:06 standard setting, use: edges=links
> 
> 15:23:06 load train
> 
> 15:23:06 load dev
> 
> dev size: 4880
> 
> 15:23:06 load test
> 
> test size: 19746
> 
> relation size: 11 entity size: 38194
> 
> Traceback (most recent call last):
> 
> File "main.py", line 330, in
> 
> ```
> main(args) 
> ```
> 
> File "main.py", line 242, in main
> 
> ```
> trLoss,Ntr = train(args,m,xp,opt) 
> ```
> 
> File "main.py", line 187, in train
> 
> ```
> loss = m.train(positive,negative,glinks,gold_relations,gedges,xp) 
> ```
> 
> File "/home/ktgroup/Documents/kems/Tools/GNN-for-OOKB/1-starndard-setting/models/ModelA0.py", line 256, in train
> 
> ```
> x = self.get_context(entities,links,relations,edges,0,xp) 
> ```
> 
> File "/home/ktgroup/Documents/kems/Tools/GNN-for-OOKB/1-starndard-setting/models/ModelA0.py", line 240, in get_context
> 
> ```
> x = getattr(self,self.forwardB[order][0])(x,neighbor,neighbor_dict,assign,entities,relations) 
> ```
> 
> File "/home/ktgroup/Documents/kems/Tools/GNN-for-OOKB/1-starndard-setting/models/ModelA0.py", line 163, in **call**
> 
> ```
> if r%2==0:    rx = getattr(self,self.forwardH[r//2][0])(rx) 
> ```
> 
> File "/home/ktgroup/Documents/kems/Tools/GNN-for-OOKB/1-starndard-setting/models/ModelA0.py", line 37, in **call**
> 
> ```
> x = getattr(self,name)(x) 
> ```
> 
> File "/home/ktgroup/Documents/kems/Tools/GNN-for-OOKB/1-starndard-setting/models/ModelA0.py", line 19, in **call**
> if self.dropout_rate!=0:
> **AttributeError: 'Module' object has no attribute 'dropout_rate'**
> 
> Could you advise me what changes that I need to do on your code to make main.py running?
> 
> Thank you very much,
> Kem

Have you figured it out?My solution is commenting out all the duplicate code(from line 11 to line 303) in ModelA0.py.
I wonder if there is a better one.
